// White-label scrub for Agency ZIP exports.
// Removes all Quante platform references from generated file content.
// Run this as a post-processing pass over GeneratedFile[] before zipping.

export interface ScrubFile {
  path: string
  content: string
  encoding?: 'utf-8' | 'base64'
}

const QUANTE_PATTERN = /quante/gi

export function scrubBranding(files: ScrubFile[]): ScrubFile[] {
  return files.map((f) => {
    // Never touch binary files
    if (f.encoding === 'base64') return f
    return { ...f, content: scrubContent(f.path, f.content) }
  })
}

function scrubContent(_filePath: string, content: string): string {
  // 1. Strip attribution lines (must run before catch-all so they're removed not just renamed)
  content = content.replace(/Generated with \*\*Quante\*\*[^\n]*/gi, '')
  content = content.replace(/built with Quante[^\n]*/gi, '')
  content = content.replace(/\*[^*]*built with Quante[^*]*\*/gi, '')

  // 2. Strip domain URLs (e.g. https://quante.vercel.app, my-store.quante.app)
  content = content.replace(/https?:\/\/[a-z0-9.-]*quante\.[a-z.]+[^\s"')>]*/gi, '')
  content = content.replace(/[a-z0-9-]+\.quante\.(app|io)[^\s"')>]*/gi, '')

  // 3. Rename localStorage key at source
  content = content.replace(/quante-cart/gi, 'store-cart')

  // 4. Catch-all: replace every remaining "quante" token, preserving case
  //    QUANTE → BUILDER, Quante → Builder, quante → builder
  content = content.replace(/QUANTE/g, 'BUILDER')
  content = content.replace(/Quante/g, 'Builder')
  content = content.replace(/quante/g, 'builder')

  return content
}

// Returns true if any file content still contains a quante reference.
// Used in the export test to assert clean output.
export function hasQuanteRefs(files: ScrubFile[]): { found: boolean; hits: string[] } {
  const hits: string[] = []
  for (const f of files) {
    if (f.encoding === 'base64') continue
    const matches = f.content.match(new RegExp(QUANTE_PATTERN.source, 'gi'))
    if (matches) {
      hits.push(`${f.path}: ${matches.slice(0, 3).join(', ')}`)
    }
  }
  return { found: hits.length > 0, hits }
}

// Generic README for agency exports
export function agencyReadme(storeName: string): string {
  return `# ${storeName}

A Next.js e-commerce project — generated by an AI builder.

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).

## Configuration

Copy \`.env.example\` to \`.env.local\` and fill in your Stripe keys:

\`\`\`bash
cp .env.example .env.local
\`\`\`

## Deployment

Deploy to [Vercel](https://vercel.com) in one click — no configuration required.
Add your environment variables in the Vercel dashboard under **Project → Settings → Environment Variables**.

## Tech stack

- **Next.js 16** (App Router)
- **TypeScript**
- **Tailwind CSS**
- **Stripe** — payment processing (your own keys)
`
}

// Generic .env.example for agency exports
export const AGENCY_ENV_EXAMPLE = `# Stripe — add your own keys from https://dashboard.stripe.com/apikeys
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_live_...
STRIPE_SECRET_KEY=sk_live_...
STRIPE_WEBHOOK_SECRET=whsec_...

# App
NEXT_PUBLIC_APP_URL=https://your-domain.com
`
